package POJOs;
// Generated Dec 3, 2018 7:32:48 AM by Hibernate Tools 4.3.1



/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer idemployees;
     private String initials;
     private String fullName;
     private Integer contactNo;
     private String designation;

    public Employees() {
    }

    public Employees(String initials, String fullName, Integer contactNo, String designation) {
       this.initials = initials;
       this.fullName = fullName;
       this.contactNo = contactNo;
       this.designation = designation;
    }
   
    public Integer getIdemployees() {
        return this.idemployees;
    }
    
    public void setIdemployees(Integer idemployees) {
        this.idemployees = idemployees;
    }
    public String getInitials() {
        return this.initials;
    }
    
    public void setInitials(String initials) {
        this.initials = initials;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Integer getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(Integer contactNo) {
        this.contactNo = contactNo;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


